version: '2'
services:
  haproxy:
    image: haproxy:alpine
    restart: always
    hostname: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - haproxy-syslog
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  haproxy-syslog:
    image: outstand/syslog-ng-stdout:latest
    restart: always
    hostname: haproxy-syslog
  http:
    image: nginx:alpine
    restart: always
    hostname: http
    expose:
    - "80"
    volumes:
    - ./letsencrypt/http:/usr/share/nginx/html:ro
  eyeserver-proxy:
    image: haproxy:alpine
    restart: always
    hostname: eyeserver-proxy
    ports:
      - "443"
    volumes_from:
      - haproxy-syslog
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./config/eyeserver-haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  eyeserver:
    image: bdevloed/eyeserver
    restart: always
    hostname: eyeserver
    ports:
    - "8000"
  sendilo:
    build: .
    restart: always
    hostname: sendilo
    ports:
    - "443"
    volumes:
    - ./letsencrypt/etc:/solid/certs:ro
    - ./config/config.json:/solid/run/config.json:ro
    - ./solid/config:/solid/config
    - ./solid/data:/solid/data
    - ./solid/db:/solid/db
    environment:
    - DEBUG=solid:*,sendilo:*

